version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"

  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - "2181:2181"